apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  namespace: default  # Ensure the namespace is correct
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name: mouss1959/flask-app
        image: flask-app:latest
        ports:
        - containerPort: 5001
