# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-web-app
  namespace: default  # Ensure the namespace is correct
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP